"""Benchmark orchestrator — runs one complete experiment scenario.

Manages the lifecycle of a single benchmark run:
  1. Instantiate and connect the correct ProtocolClient.
  2. Register callbacks to collect MetricRecords as messages arrive.
  3. Drive the scenario (send commands / wait for telemetry) for the run duration.
  4. Disconnect and return the collected records + run metadata.

Designed to be called from a background thread in the Streamlit benchmark page.
All cross-thread communication happens via threading.Event (stop_event) and a
callback queue passed in by the UI.

See docs/benchmark-flow.md and docs/ai-context/frontend-dev.md for the
full run flow and metric definitions.
"""
import json
import queue
import threading
import time
from dataclasses import dataclass, asdict
from typing import Callable, Optional

from .config import Config
from .logger import MetricRecord, next_run_id, save_run
from .protocols.base import ProtocolClient
from .protocols.http_client import HttpClient
from .protocols.mqtt_client import MqttClient
from .protocols.websocket_client import WebSocketClient
from .protocols.coap_client import CoapClient


@dataclass
class RunConfig:
    """Parameters for a single benchmark run.

    run_id is auto-generated by next_run_id() if left empty.
    """
    protocol: str           # mqtt | http | websocket | coap
    scenario: int           # 1 | 2 | 3
    rate_msg_s: Optional[int]   # Scenario 1 only: 1, 5, or 10 msg/s
    n_commands: int         # Scenario 2: 50; Scenario 1: rate × duration_s
    duration_s: int         # Scenario 1 & 3: 300 s; Scenario 2: from n_commands
    # Scenario 2: wall-clock cap for the entire burst.
    # Budget = n_commands × (per_cmd_ack_timeout + send_latency).
    # 50 cmds × 10 s/cmd + margin = 600 s is a safe ceiling.
    ack_run_timeout_s: int = 600
    # Scenario 2: delay between consecutive commands (ms). 0 = maximum burst.
    # A small delay (200–500 ms) lets the CSE deliver notifications to Android
    # before the next command arrives, reducing notification backlog and improving
    # delivery reliability at the cost of total burst duration.
    inter_command_delay_ms: int = 0
    run_id: str = ""        # auto-generated if empty
    notes: str = ""         # operator notes for the JSON sidecar


@dataclass
class RunResult:
    """Returned by run() after a benchmark completes."""
    run_id: str
    records: list[MetricRecord]
    csv_path: str           # path to the written CSV file
    n_delivered: int
    n_total: int
    mean_latency_ms: Optional[float]


def _make_client(protocol: str, config: Config) -> ProtocolClient:
    """Instantiate the correct ProtocolClient for the given protocol string."""
    mapping = {
        "websocket": WebSocketClient,
        "mqtt": MqttClient,
        "http": HttpClient,
        "coap": CoapClient,
    }
    cls = mapping.get(protocol.lower())
    if cls is None:
        raise ValueError(f"Unknown protocol: {protocol!r}. Use one of {list(mapping)}")
    return cls(config)


def run(
    run_cfg: RunConfig,
    config: Config,
    stop_event: threading.Event,
    progress_cb: Optional[Callable[[int, int, list[MetricRecord]], None]] = None,
) -> RunResult:
    """Execute a complete benchmark run and write results to data/raw/.

    Parameters
    ----------
    run_cfg : RunConfig
    config : Config — connection parameters from .env
    stop_event : threading.Event — set by the UI to abort mid-run
    progress_cb : Optional callback invoked after each message, with
                  (n_delivered, n_total, records_so_far) for live UI updates.

    Returns
    -------
    RunResult
    """
    if not run_cfg.run_id:
        run_cfg.run_id = next_run_id(
            run_cfg.protocol, run_cfg.scenario, config.data_raw_dir, run_cfg.rate_msg_s
        )

    client = _make_client(run_cfg.protocol, config)
    records: list[MetricRecord] = []
    records_lock = threading.Lock()
    n_total = 0
    n_delivered = 0

    # Capture run start time before any I/O for accurate sidecar reproducibility field.
    start_timestamp_ms = time.time_ns() // 1_000_000

    if run_cfg.scenario == 1:
        n_total = (run_cfg.rate_msg_s or 1) * run_cfg.duration_s
        records, n_delivered = _run_scenario_1(
            client, run_cfg, config, records_lock, stop_event, progress_cb
        )
    elif run_cfg.scenario == 2:
        n_total = run_cfg.n_commands
        records, n_delivered = _run_scenario_2(
            client, run_cfg, config, records_lock, stop_event, progress_cb
        )
    else:
        raise ValueError(f"Scenario {run_cfg.scenario} not implemented (3 is planned post-deadline)")

    csv_path = save_run(
        records=records,
        run_id=run_cfg.run_id,
        protocol=run_cfg.protocol,
        scenario=run_cfg.scenario,
        run_config_dict=asdict(run_cfg),
        data_raw_dir=config.data_raw_dir,
        notes=run_cfg.notes,
        start_timestamp_ms=start_timestamp_ms,
    )

    delivered_records = [r for r in records if r.delivered and r.latency_ms is not None]
    mean_lat = (
        sum(r.latency_ms for r in delivered_records) / len(delivered_records)
        if delivered_records else None
    )

    return RunResult(
        run_id=run_cfg.run_id,
        records=records,
        csv_path=str(csv_path),
        n_delivered=n_delivered,
        # Use the expected message count (not received) so loss % is meaningful.
        n_total=n_total,
        mean_latency_ms=mean_lat,
    )


# ------------------------------------------------------------------
# Scenario implementations
# ------------------------------------------------------------------

def _run_scenario_1(
    client: ProtocolClient,
    run_cfg: RunConfig,
    config: Config,
    lock: threading.Lock,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 1: passive telemetry collection over duration_s seconds.

    Steps:
      1. Connect + subscribe to telemetry
      2. Send setTelemetryRate command to configure the drone's emission rate
      3. Collect telemetry CINs until duration_s elapsed or stop_event set
      4. Disconnect

    Latency = timestamp_ms (Streamlit receive) - t_send_ms (Android send).
    NTP-dependent: both dev machine and RC must be NTP-synced on the same LAN.
    """
    records: list[MetricRecord] = []
    n_delivered = 0
    interval_ms = _rate_to_interval_ms(run_cfg.rate_msg_s or 1)

    tel_queue: queue.Queue = queue.Queue()

    def on_telemetry(con: dict) -> None:
        tel_queue.put((time.time_ns() // 1_000_000, con))

    client.subscribe_telemetry(on_telemetry)

    try:
        client.connect()

        # Ask Android to emit at the target rate.
        client.send_command({"command": "setTelemetryRate", "intervalMs": interval_ms})

        t_deadline = time.monotonic() + run_cfg.duration_s
        seq_local = 0

        while not stop_event.is_set() and time.monotonic() < t_deadline:
            try:
                timestamp_ms, con = tel_queue.get(timeout=1.0)
            except queue.Empty:
                continue

            seq_local += 1
            android_seq = con.get("seq", seq_local)
            t_send_ms = con.get("t_send_ms")
            payload_str = json.dumps(con)
            payload_bytes = len(payload_str.encode())
            header_bytes = client.get_header_bytes(payload_bytes)

            # Latency is NTP-dependent: both devices must be synced to the same clock.
            # Raw delta is kept (can be negative) — negative values indicate the Android
            # clock is ahead of the dev-machine clock (clock offset, not real latency).
            # Do NOT clamp to 0 here: the raw value is needed to detect/correct the offset
            # in the analysis phase. Document the NTP dependency in the paper methodology.
            latency_ms: Optional[float] = None
            if t_send_ms is not None:
                raw_delta = timestamp_ms - t_send_ms
                latency_ms = float(raw_delta)
                # Log first 3 packets per run to diagnose clock offset
                if seq_local <= 3:
                    print(
                        f"[{time.strftime('%H:%M:%S')}][S1] seq={android_seq} t_send_ms={t_send_ms} "
                        f"timestamp_ms={timestamp_ms} delta={raw_delta:+.0f} ms",
                        flush=True,
                    )

            rec = MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=1,
                direction="telemetry",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=header_bytes,
                delivered=True,
                seq=android_seq,
                t_send_ms=t_send_ms,
                t_cmd_ms=None,
                t_recv_ms=None,
                t_exec_ms=None,
                cin_create_ms=None,  # telemetry rows: no command sent from Streamlit
            )
            with lock:
                records.append(rec)
                n_delivered += 1

            if progress_cb:
                progress_cb(n_delivered, n_delivered, list(records))

    finally:
        client.disconnect()

    return records, n_delivered


def _run_scenario_2(
    client: ProtocolClient,
    run_cfg: RunConfig,
    config: Config,
    lock: threading.Lock,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 2: send n_commands commands and collect ACKs.

    Sends commands in a rotating set (takeoff/land alternating) to avoid
    drone state conflicts. Waits for each ACK before sending the next command.

    Latency = t_recv_ms - t_cmd_ms.
    NOTE: t_cmd_ms is set by Streamlit (dev machine clock) and t_recv_ms by
    Android (RC clock). Both are wall-clock times and NTP-dependent in practice,
    despite the "device-to-device" description in the docs. For the paper,
    note that both devices are on the same LAN and NTP-synced.
    """
    records: list[MetricRecord] = []
    n_delivered = 0

    ack_queue: queue.Queue = queue.Queue()

    def on_ack(con: dict) -> None:
        ack_queue.put(con)

    client.subscribe_ack(on_ack)

    try:
        client.connect()

        run_deadline = time.monotonic() + run_cfg.ack_run_timeout_s

        for seq_cmd in range(1, run_cfg.n_commands + 1):
            if stop_event.is_set():
                break
            if time.monotonic() >= run_deadline:
                print(
                    f"[{time.strftime('%H:%M:%S')}][S2] run timeout ({run_cfg.ack_run_timeout_s}s) reached after "
                    f"{seq_cmd - 1}/{run_cfg.n_commands} commands — aborting burst",
                    flush=True,
                )
                break

            # Alternate identify state (false/true) — simple, stateless, safe to repeat.
            state = (seq_cmd % 2 == 0)
            t_cmd_ms = int(time.time() * 1000)
            payload = {
                "command": "identify",
                "state": state,
                "seq_cmd": seq_cmd,
                "t_cmd_ms": t_cmd_ms,
            }
            payload_str = json.dumps(payload)
            payload_bytes = len(payload_str.encode())

            send_latency_ms, send_ok = client.send_command(payload)
            header_bytes = client.get_header_bytes(payload_bytes)
            timestamp_ms = time.time_ns() // 1_000_000

            if not send_ok:
                # CIN creation failed — record as undelivered; no ACK possible.
                rec = MetricRecord(
                    timestamp_ms=timestamp_ms,
                    run_id=run_cfg.run_id,
                    protocol=run_cfg.protocol,
                    scenario=2,
                    direction="command",
                    latency_ms=None,
                    payload_bytes=payload_bytes,
                    header_bytes=header_bytes,
                    delivered=False,
                    seq=seq_cmd,
                    t_send_ms=None,
                    t_cmd_ms=t_cmd_ms,
                    t_recv_ms=None,
                    t_exec_ms=None,
                    cin_create_ms=None,  # failed — no round-trip time available
                )
                with lock:
                    records.append(rec)
                continue

            # CIN creation succeeded: record the Streamlit→CSE round-trip separately.
            cin_create_ms: Optional[float] = send_latency_ms

            # Per-command ACK timeout, clamped to the remaining run budget so the
            # overall ack_run_timeout_s is always respected.
            # Drain the queue until the matching seq_cmd arrives or time runs out.
            # A single get() is not enough: a late ACK from a previous command can
            # contaminate the queue and cause a cascade of false misses.
            remaining_s = max(0.0, run_deadline - time.monotonic())
            ack_deadline = time.monotonic() + min(10.0, remaining_s)
            ack_con = None
            while time.monotonic() < ack_deadline:
                try:
                    candidate = ack_queue.get(timeout=max(0.0, ack_deadline - time.monotonic()))
                    if candidate.get("seq_cmd") == seq_cmd:
                        ack_con = candidate
                        break
                    # Stale/mismatched ACK — discard and keep waiting
                    print(
                        f"[{time.strftime('%H:%M:%S')}][S2] discarded stale ACK seq_cmd={candidate.get('seq_cmd')} "
                        f"(waiting for {seq_cmd})",
                        flush=True,
                    )
                except queue.Empty:
                    break

            if ack_con:
                t_recv_ms = ack_con.get("t_recv_ms")
                t_exec_ms = ack_con.get("t_exec_ms")
                # End-to-end latency: Android receive minus Streamlit send (NTP-dependent).
                # Null when t_recv_ms not returned — do NOT fall back to cin_create_ms,
                # which measures a different path (Streamlit→CSE only).
                latency_ms: Optional[float] = (
                    (t_recv_ms - t_cmd_ms) if t_recv_ms is not None else None
                )
                delivered = True
                n_delivered += 1
            else:
                t_recv_ms = None
                t_exec_ms = None
                latency_ms = None   # ACK timeout — no end-to-end measurement
                delivered = False

            rec = MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=2,
                direction="command",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=header_bytes,
                delivered=delivered,
                seq=seq_cmd,
                t_send_ms=None,
                t_cmd_ms=t_cmd_ms,
                t_recv_ms=t_recv_ms,
                t_exec_ms=t_exec_ms,
                cin_create_ms=cin_create_ms,
            )
            with lock:
                records.append(rec)

            if progress_cb:
                progress_cb(n_delivered, seq_cmd, list(records))

            if run_cfg.inter_command_delay_ms > 0:
                time.sleep(run_cfg.inter_command_delay_ms / 1000.0)

    finally:
        client.disconnect()

    return records, n_delivered


def _rate_to_interval_ms(rate_msg_s: int) -> int:
    """Convert msg/s rate to intervalMs for the setTelemetryRate command."""
    return max(100, 1000 // rate_msg_s)
