"""Benchmark orchestrator — runs one complete experiment scenario.

Manages the lifecycle of a single benchmark run:
  1. Instantiate and connect the correct ProtocolClient.
  2. Register callbacks to collect MetricRecords as messages arrive.
  3. Drive the scenario (send commands / wait for telemetry) for the run duration.
  4. Disconnect and return the collected records + run metadata.

Designed to be called from a background thread in the Streamlit benchmark page.
All cross-thread communication happens via threading.Event (stop_event) and a
callback queue passed in by the UI.

See docs/benchmark-flow.md and docs/ai-context/frontend-dev.md for the
full run flow and metric definitions.
"""
import json
import queue
import threading
import time
from dataclasses import dataclass, asdict
from typing import Callable, Optional

from .config import Config
from .logger import MetricRecord, next_run_id, save_run
from .protocols.base import ProtocolClient
from .protocols.http_client import HttpClient
from .protocols.mqtt_client import MqttClient
from .protocols.websocket_client import WebSocketClient
from .protocols.coap_client import CoapClient


@dataclass
class RunConfig:
    """Parameters for a single benchmark run.

    run_id is auto-generated by next_run_id() if left empty.
    """
    protocol: str           # mqtt | http | websocket | coap
    scenario: int           # 1 | 2 | 3
    rate_msg_s: Optional[int]   # Scenario 1 only: 1, 5, or 10 msg/s
    n_commands: int         # Scenario 2: 50; Scenario 1: rate × duration_s
    duration_s: int         # Scenario 1 & 3: 300 s; Scenario 2: from n_commands
    run_id: str = ""        # auto-generated if empty
    notes: str = ""         # operator notes for the JSON sidecar


@dataclass
class RunResult:
    """Returned by run() after a benchmark completes."""
    run_id: str
    records: list[MetricRecord]
    csv_path: str           # path to the written CSV file
    n_delivered: int
    n_total: int
    mean_latency_ms: Optional[float]


def _make_client(protocol: str, config: Config) -> ProtocolClient:
    """Instantiate the correct ProtocolClient for the given protocol string."""
    mapping = {
        "websocket": WebSocketClient,
        "mqtt": MqttClient,
        "http": HttpClient,
        "coap": CoapClient,
    }
    cls = mapping.get(protocol.lower())
    if cls is None:
        raise ValueError(f"Unknown protocol: {protocol!r}. Use one of {list(mapping)}")
    return cls(config)


def run(
    run_cfg: RunConfig,
    config: Config,
    stop_event: threading.Event,
    progress_cb: Optional[Callable[[int, int, list[MetricRecord]], None]] = None,
) -> RunResult:
    """Execute a complete benchmark run and write results to data/raw/.

    Parameters
    ----------
    run_cfg : RunConfig
    config : Config — connection parameters from .env
    stop_event : threading.Event — set by the UI to abort mid-run
    progress_cb : Optional callback invoked after each message, with
                  (n_delivered, n_total, records_so_far) for live UI updates.

    Returns
    -------
    RunResult
    """
    if not run_cfg.run_id:
        run_cfg.run_id = next_run_id(run_cfg.protocol, run_cfg.scenario, config.data_raw_dir)

    client = _make_client(run_cfg.protocol, config)
    records: list[MetricRecord] = []
    records_lock = threading.Lock()
    n_total = 0
    n_delivered = 0

    if run_cfg.scenario == 1:
        n_total = (run_cfg.rate_msg_s or 1) * run_cfg.duration_s
        records, n_delivered = _run_scenario_1(
            client, run_cfg, config, records_lock, stop_event, progress_cb
        )
    elif run_cfg.scenario == 2:
        n_total = run_cfg.n_commands
        records, n_delivered = _run_scenario_2(
            client, run_cfg, config, records_lock, stop_event, progress_cb
        )
    else:
        raise ValueError(f"Scenario {run_cfg.scenario} not implemented (3 is planned post-deadline)")

    csv_path = save_run(
        records=records,
        run_id=run_cfg.run_id,
        protocol=run_cfg.protocol,
        scenario=run_cfg.scenario,
        run_config_dict=asdict(run_cfg),
        data_raw_dir=config.data_raw_dir,
        notes=run_cfg.notes,
    )

    delivered_records = [r for r in records if r.delivered and r.latency_ms is not None]
    mean_lat = (
        sum(r.latency_ms for r in delivered_records) / len(delivered_records)
        if delivered_records else None
    )

    return RunResult(
        run_id=run_cfg.run_id,
        records=records,
        csv_path=str(csv_path),
        n_delivered=n_delivered,
        n_total=len(records),
        mean_latency_ms=mean_lat,
    )


# ------------------------------------------------------------------
# Scenario implementations
# ------------------------------------------------------------------

def _run_scenario_1(
    client: ProtocolClient,
    run_cfg: RunConfig,
    config: Config,
    lock: threading.Lock,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 1: passive telemetry collection over duration_s seconds.

    Steps:
      1. Connect + subscribe to telemetry
      2. Send setTelemetryRate command to configure the drone's emission rate
      3. Collect telemetry CINs until duration_s elapsed or stop_event set
      4. Disconnect

    Latency = timestamp_ms (Streamlit receive) - t_send_ms (Android send).
    NTP-dependent: both dev machine and RC must be NTP-synced on the same LAN.
    """
    records: list[MetricRecord] = []
    n_delivered = 0
    interval_ms = _rate_to_interval_ms(run_cfg.rate_msg_s or 1)

    tel_queue: queue.Queue = queue.Queue()

    def on_telemetry(con: dict) -> None:
        tel_queue.put((time.time_ns() // 1_000_000, con))

    client.subscribe_telemetry(on_telemetry)

    try:
        client.connect()

        # Ask Android to emit at the target rate.
        client.send_command({"command": "setTelemetryRate", "intervalMs": interval_ms})

        t_deadline = time.monotonic() + run_cfg.duration_s
        seq_local = 0

        while not stop_event.is_set() and time.monotonic() < t_deadline:
            try:
                timestamp_ms, con = tel_queue.get(timeout=1.0)
            except queue.Empty:
                continue

            seq_local += 1
            android_seq = con.get("seq", seq_local)
            t_send_ms = con.get("t_send_ms")
            payload_str = json.dumps(con)
            payload_bytes = len(payload_str.encode())
            header_bytes = client.get_header_bytes(payload_bytes)

            # Latency is NTP-dependent: both devices must be synced to the same clock.
            latency_ms: Optional[float] = None
            if t_send_ms is not None:
                latency_ms = max(0.0, timestamp_ms - t_send_ms)

            rec = MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=1,
                direction="telemetry",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=header_bytes,
                delivered=True,
                seq=android_seq,
                t_send_ms=t_send_ms,
                t_cmd_ms=None,
                t_recv_ms=None,
                t_exec_ms=None,
            )
            with lock:
                records.append(rec)
                n_delivered += 1

            if progress_cb:
                progress_cb(n_delivered, n_delivered, list(records))

    finally:
        client.disconnect()

    return records, n_delivered


def _run_scenario_2(
    client: ProtocolClient,
    run_cfg: RunConfig,
    config: Config,
    lock: threading.Lock,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 2: send n_commands commands and collect ACKs.

    Sends commands in a rotating set (takeoff/land alternating) to avoid
    drone state conflicts. Waits for each ACK before sending the next command.

    Latency = t_recv_ms - t_cmd_ms.
    NOTE: t_cmd_ms is set by Streamlit (dev machine clock) and t_recv_ms by
    Android (RC clock). Both are wall-clock times and NTP-dependent in practice,
    despite the "device-to-device" description in the docs. For the paper,
    note that both devices are on the same LAN and NTP-synced.
    """
    records: list[MetricRecord] = []
    n_delivered = 0

    # State-independent commands — safe to rotate without drone state knowledge.
    _COMMANDS = ["identify", "gimbalReset", "setZoom", "setCameraMode"]

    ack_queue: queue.Queue = queue.Queue()

    def on_ack(con: dict) -> None:
        ack_queue.put(con)

    client.subscribe_ack(on_ack)

    try:
        client.connect()

        for seq_cmd in range(1, run_cfg.n_commands + 1):
            if stop_event.is_set():
                break

            command = _COMMANDS[(seq_cmd - 1) % len(_COMMANDS)]
            t_cmd_ms = int(time.time() * 1000)
            payload = {
                "command": command,
                "seq_cmd": seq_cmd,
                "t_cmd_ms": t_cmd_ms,
            }
            payload_str = json.dumps(payload)
            payload_bytes = len(payload_str.encode())

            send_latency_ms, send_ok = client.send_command(payload)
            header_bytes = client.get_header_bytes(payload_bytes)
            timestamp_ms = time.time_ns() // 1_000_000

            if not send_ok:
                # CIN creation failed — record as undelivered.
                rec = MetricRecord(
                    timestamp_ms=timestamp_ms,
                    run_id=run_cfg.run_id,
                    protocol=run_cfg.protocol,
                    scenario=2,
                    direction="command",
                    latency_ms=None,
                    payload_bytes=payload_bytes,
                    header_bytes=header_bytes,
                    delivered=False,
                    seq=seq_cmd,
                    t_send_ms=None,
                    t_cmd_ms=t_cmd_ms,
                    t_recv_ms=None,
                    t_exec_ms=None,
                )
                with lock:
                    records.append(rec)
                continue

            # Wait for ACK from Android (delivered via subscription).
            ack_timeout_s = 10.0
            try:
                ack_con = ack_queue.get(timeout=ack_timeout_s)
            except queue.Empty:
                ack_con = None

            if ack_con and ack_con.get("seq_cmd") == seq_cmd:
                t_recv_ms = ack_con.get("t_recv_ms")
                t_exec_ms = ack_con.get("t_exec_ms")
                # Latency: device-to-device, both clocks NTP-synced on same LAN.
                latency_ms = (
                    (t_recv_ms - t_cmd_ms) if t_recv_ms is not None else send_latency_ms
                )
                delivered = True
                n_delivered += 1
            else:
                t_recv_ms = None
                t_exec_ms = None
                latency_ms = None
                delivered = False

            rec = MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=2,
                direction="command",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=header_bytes,
                delivered=delivered,
                seq=seq_cmd,
                t_send_ms=None,
                t_cmd_ms=t_cmd_ms,
                t_recv_ms=t_recv_ms,
                t_exec_ms=t_exec_ms,
            )
            with lock:
                records.append(rec)

            if progress_cb:
                progress_cb(n_delivered, seq_cmd, list(records))

    finally:
        client.disconnect()

    return records, n_delivered


def _rate_to_interval_ms(rate_msg_s: int) -> int:
    """Convert msg/s rate to intervalMs for the setTelemetryRate command."""
    return max(100, 1000 // rate_msg_s)
