"""Benchmark orchestrator — runs one complete experiment scenario.

Manages the lifecycle of a single benchmark run:
  1. Instantiate and connect the correct ProtocolClient.
  2. Register callbacks to collect MetricRecords as messages arrive.
  3. Drive the scenario (send commands / wait for telemetry) for the run duration.
  4. Disconnect and return the collected records + run metadata.

Designed to be called from a background thread in the Streamlit benchmark page.
All cross-thread communication happens via threading.Event (stop_event) and a
callback queue passed in by the UI.

See docs/ai-context/frontend-dev.md for the full run flow and metric definitions.

Authors: João Parreira, Pedro Barbeiro
"""
import json
import queue
import threading
import time
from dataclasses import dataclass, asdict
from typing import Callable, Optional

from .config import Config
from .logger import MetricRecord, next_run_id, save_run
from .protocols.base import ProtocolClient
from .protocols.http_client import HttpClient
from .protocols.mqtt_client import MqttClient
from .protocols.websocket_client import WebSocketClient
from .protocols.coap_client import CoapClient


@dataclass
class RunConfig:
    """Parameters for a single benchmark run.

    run_id is auto-generated by next_run_id() if left empty.
    """
    protocol: str                # mqtt | http | websocket | coap
    scenario: int                # 1 (telemetry) | 2 (commands / ping)
    rate_msg_s: Optional[int]    # Scenario 1 only: 4 or 16 msg/s
    n_commands: int              # Scenario 2: 60 ping commands at 1/s
    duration_s: int              # Scenario 1: 60 s
    # Wall-clock cap for the entire command burst (scenario 2).
    # 60 cmds × (10 s ACK timeout + 1 s delay) = 660 s absolute worst case.
    ack_run_timeout_s: int = 300
    # Delay between consecutive commands (ms), applied after each ACK.
    # 1000 ms ≈ 1 cmd/s; 60 cmds × 1 s ≈ 1 min per run.
    inter_command_delay_ms: int = 1000
    run_id: str = ""             # auto-generated if empty
    notes: str = ""              # operator notes for the JSON sidecar


@dataclass
class RunResult:
    """Returned by run() after a benchmark completes."""
    run_id: str
    records: list[MetricRecord]
    csv_path: str
    n_delivered: int
    n_total: int
    mean_latency_ms: Optional[float]


def _make_client(protocol: str, config: Config) -> ProtocolClient:
    """Instantiate the correct ProtocolClient for the given protocol string."""
    mapping = {
        "websocket": WebSocketClient,
        "mqtt":      MqttClient,
        "http":      HttpClient,
        "coap":      CoapClient,
    }
    cls = mapping.get(protocol.lower())
    if cls is None:
        raise ValueError(f"Unknown protocol: {protocol!r}. Use one of {list(mapping)}")
    return cls(config)


def run(
    run_cfg: RunConfig,
    config: Config,
    stop_event: threading.Event,
    progress_cb: Optional[Callable[[int, int, list[MetricRecord]], None]] = None,
) -> RunResult:
    """Execute a complete benchmark run and write results to data/raw/.

    Parameters
    ----------
    run_cfg    : RunConfig
    config     : Config — connection parameters from .env
    stop_event : threading.Event — set by the UI to abort mid-run
    progress_cb: Optional callback(n_delivered, n_total, records_so_far) for live UI updates.

    Returns
    -------
    RunResult
    """
    if not run_cfg.run_id:
        run_cfg.run_id = next_run_id(
            run_cfg.protocol, run_cfg.scenario, config.data_raw_dir, run_cfg.rate_msg_s,
        )

    client = _make_client(run_cfg.protocol, config)
    start_timestamp_ms = time.time_ns() // 1_000_000

    if run_cfg.scenario == 1:
        n_total = (run_cfg.rate_msg_s or 1) * run_cfg.duration_s
        records, n_delivered = _run_scenario_1(client, run_cfg, stop_event, progress_cb)
    else:
        n_total = run_cfg.n_commands
        records, n_delivered = _run_scenario_2(client, run_cfg, stop_event, progress_cb)

    csv_path = save_run(
        records=records,
        run_id=run_cfg.run_id,
        protocol=run_cfg.protocol,
        scenario=run_cfg.scenario,
        run_config_dict=asdict(run_cfg),
        data_raw_dir=config.data_raw_dir,
        notes=run_cfg.notes,
        start_timestamp_ms=start_timestamp_ms,
    )

    delivered_records = [r for r in records if r.delivered and r.latency_ms is not None]
    mean_lat = (
        sum(r.latency_ms for r in delivered_records) / len(delivered_records)
        if delivered_records else None
    )

    return RunResult(
        run_id=run_cfg.run_id,
        records=records,
        csv_path=str(csv_path),
        n_delivered=n_delivered,
        # Use the expected message count (not received) so loss % is meaningful.
        n_total=n_total,
        mean_latency_ms=mean_lat,
    )


# ------------------------------------------------------------------
# Scenario implementations
# ------------------------------------------------------------------

# Warmup drain windows (seconds) at the start of each scenario.
#
# S1 drain: discards stale telemetry notifications from the CSE TinyDB queue that
# predate this run. At reconnect the CSE replays any backlogged notifications —
# observed: run002 received 421/240, mean latency 96 s after an uncleared backlog.
# 3 s covers normal inter-run backlog at 4 msg/s; for 16 msg/s sessions do
# `docker compose restart` first.
#
# S3 drain: discards stale ACKs (incl. the setTelemetryRate ACK from setup) and
# gives the CSE asyncio event loop time to flush any residual TinyDB backlog from
# a prior telemetry session. Without this, the CSE event loop stays busy delivering
# backlogged telemetry notifications and delays ACK notifications past the 10 s
# timeout — observed: 8/60 ACKs lost in WS S3 run 55 s after WS S1 r16.
_S1_DRAIN_S = 3.0
_S3_DRAIN_S = 3.0


def _drain_stale(q: queue.Queue, drain_s: float) -> int:
    """Discard all items arriving in q for drain_s seconds.

    Parameters
    ----------
    q       : Queue to drain (telemetry or ack queue).
    drain_s : How many seconds to discard incoming items.

    Returns
    -------
    int — number of items discarded.
    """
    n = 0
    t_end = time.monotonic() + drain_s
    while time.monotonic() < t_end:
        try:
            q.get_nowait()
            n += 1
        except queue.Empty:
            time.sleep(0.05)
    return n


def _run_scenario_1(
    client: ProtocolClient,
    run_cfg: RunConfig,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 1 — passive telemetry collection over duration_s seconds.

    Steps:
      1. Connect + subscribe to telemetry
      2. Send setTelemetryRate to configure the Android emission rate
      3. Drain stale CSE notifications for _S1_DRAIN_S seconds (warmup)
      4. Collect CINs for duration_s seconds or until stop_event set
      5. Slow telemetry back down, then disconnect

    Latency = timestamp_ms (Streamlit receive) − t_send_ms (Android send).
    NTP-dependent: both clocks must be synced on the same LAN.
    Raw delta is kept (can be negative) — offset correction in analysis.
    """
    records: list[MetricRecord] = []
    n_delivered = 0
    interval_ms = max(50, 1000 // (run_cfg.rate_msg_s or 1))

    tel_queue: queue.Queue = queue.Queue()

    def on_telemetry(con: dict) -> None:
        tel_queue.put((time.time_ns() // 1_000_000, con))

    client.subscribe_telemetry(on_telemetry)

    try:
        client.connect()
        client.send_command({"command": "setTelemetryRate", "intervalMs": interval_ms})

        # Drain stale CSE queue before starting the measurement window.
        n_stale = _drain_stale(tel_queue, _S1_DRAIN_S)
        if n_stale:
            print(
                f"[{time.strftime('%H:%M:%S')}][S1] drained {n_stale} stale notifications",
                flush=True,
            )

        t_deadline = time.monotonic() + run_cfg.duration_s

        while not stop_event.is_set() and time.monotonic() < t_deadline:
            try:
                timestamp_ms, con = tel_queue.get(timeout=1.0)
            except queue.Empty:
                continue

            android_seq = con["seq"]
            t_send_ms = con.get("t_send_ms")
            payload_str = json.dumps(con)
            payload_bytes = len(payload_str.encode())

            latency_ms: Optional[float] = None
            if t_send_ms is not None:
                latency_ms = float(timestamp_ms - t_send_ms)
                if n_delivered < 3:  # log first 3 packets to help diagnose clock offset
                    print(
                        f"[{time.strftime('%H:%M:%S')}][S1] seq={android_seq} "
                        f"t_send={t_send_ms} t_recv={timestamp_ms} delta={latency_ms:+.0f} ms",
                        flush=True,
                    )

            records.append(MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=1,
                direction="telemetry",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=client.get_header_bytes(payload_bytes),
                delivered=True,
                seq=android_seq,
                t_send_ms=t_send_ms,
                t_cmd_ms=None,
                t_recv_ms=None,
                t_exec_ms=None,
                cin_create_ms=None,
            ))
            n_delivered += 1

            if progress_cb:
                # Pass time-based expected count so the UI can show real packet loss.
                # elapsed_s = how many seconds of the 60 s window have actually passed.
                elapsed_s = run_cfg.duration_s - max(0.0, t_deadline - time.monotonic())
                n_expected_so_far = int((run_cfg.rate_msg_s or 1) * elapsed_s)
                progress_cb(n_delivered, n_expected_so_far, list(records))

    finally:
        # Pause Android telemetry before disconnect so the CSE event loop is not
        # further saturated between runs.
        try:
            client.send_command({"command": "setTelemetryRate", "intervalMs": 60000})
        except Exception:
            pass
        client.disconnect()

    return records, n_delivered


def _run_scenario_2(
    client: ProtocolClient,
    run_cfg: RunConfig,
    stop_event: threading.Event,
    progress_cb: Optional[Callable],
) -> tuple[list[MetricRecord], int]:
    """Scenario 2 — send n_commands ping commands and wait for each ACK.

    Steps:
      1. Connect + subscribe to ACK channel
      2. Pause Android telemetry (eliminates background CSE load)
      3. For each command: create CIN, wait for matching ACK, record metrics
      4. Disconnect

    Metrics per command:
      cin_create_ms — Streamlit→CSE round-trip (monotonic, NTP-free)
      latency_ms    — t_recv_ms − t_cmd_ms (NTP-dependent, can be negative)
      delivered     — True if matching ACK arrives within 10 s timeout
    """
    records: list[MetricRecord] = []
    n_delivered = 0

    ack_queue: queue.Queue = queue.Queue()

    def on_ack(con: dict) -> None:
        ack_queue.put(con)

    client.subscribe_ack(on_ack)

    try:
        client.connect()

        # Reduce Android telemetry to near-zero: concurrent TinyDB writes block
        # the CSE asyncio event loop and inflate ACK notification latency.
        client.send_command({"command": "setTelemetryRate", "intervalMs": 60000})
        # Drain stale ACKs (incl. the setTelemetryRate ACK) and give the CSE asyncio
        # event loop time to flush any TinyDB backlog from a prior telemetry session.
        # Without this, ACK notifications for early ping commands arrive after the
        # 10 s timeout (observed: 8/60 undelivered in WS S3 run 55 s after S1 r16).
        n_stale = _drain_stale(ack_queue, _S3_DRAIN_S)
        if n_stale:
            print(
                f"[{time.strftime('%H:%M:%S')}][S3] drained {n_stale} stale ACKs",
                flush=True,
            )

        run_deadline = time.monotonic() + run_cfg.ack_run_timeout_s

        for seq_cmd in range(1, run_cfg.n_commands + 1):
            if stop_event.is_set():
                break
            if time.monotonic() >= run_deadline:
                print(
                    f"[{time.strftime('%H:%M:%S')}][S2] timeout after "
                    f"{seq_cmd - 1}/{run_cfg.n_commands} commands",
                    flush=True,
                )
                break

            t_cmd_ms = int(time.time() * 1000)
            payload = {"command": "ping", "seq_cmd": seq_cmd, "t_cmd_ms": t_cmd_ms}
            payload_str = json.dumps(payload)
            payload_bytes = len(payload_str.encode())

            send_latency_ms, send_ok = client.send_command(payload)
            header_bytes = client.get_header_bytes(payload_bytes)
            timestamp_ms = time.time_ns() // 1_000_000

            if not send_ok:
                # CIN creation failed — record as undelivered; no ACK possible.
                records.append(MetricRecord(
                    timestamp_ms=timestamp_ms,
                    run_id=run_cfg.run_id,
                    protocol=run_cfg.protocol,
                    scenario=2,
                    direction="command",
                    latency_ms=None,
                    payload_bytes=payload_bytes,
                    header_bytes=header_bytes,
                    delivered=False,
                    seq=seq_cmd,
                    t_send_ms=None,
                    t_cmd_ms=t_cmd_ms,
                    t_recv_ms=None,
                    t_exec_ms=None,
                    cin_create_ms=None,
                ))
                continue

            # Wait for the matching ACK; drain stale ACKs from prior commands.
            remaining_s = max(0.0, run_deadline - time.monotonic())
            ack_deadline = time.monotonic() + min(10.0, remaining_s)
            ack_con = None
            while time.monotonic() < ack_deadline:
                try:
                    candidate = ack_queue.get(timeout=max(0.0, ack_deadline - time.monotonic()))
                    if candidate.get("seq_cmd") == seq_cmd:
                        ack_con = candidate
                        break
                    print(
                        f"[{time.strftime('%H:%M:%S')}][S2] stale ACK "
                        f"seq_cmd={candidate.get('seq_cmd')} (want {seq_cmd})",
                        flush=True,
                    )
                except queue.Empty:
                    break

            if ack_con:
                t_recv_ms = ack_con.get("t_recv_ms")
                t_exec_ms = ack_con.get("t_exec_ms")
                # NTP-dependent: RC clock typically ~1.88 s behind dev machine.
                # Raw negative values are kept for offset correction in analysis.
                latency_ms: Optional[float] = (
                    float(t_recv_ms - t_cmd_ms) if t_recv_ms is not None else None
                )
                delivered = True
                n_delivered += 1
            else:
                t_recv_ms = t_exec_ms = None
                latency_ms = None
                delivered = False

            records.append(MetricRecord(
                timestamp_ms=timestamp_ms,
                run_id=run_cfg.run_id,
                protocol=run_cfg.protocol,
                scenario=2,
                direction="command",
                latency_ms=latency_ms,
                payload_bytes=payload_bytes,
                header_bytes=header_bytes,
                delivered=delivered,
                seq=seq_cmd,
                t_send_ms=None,
                t_cmd_ms=t_cmd_ms,
                t_recv_ms=t_recv_ms,
                t_exec_ms=t_exec_ms,
                cin_create_ms=float(send_latency_ms),
            ))

            if progress_cb:
                progress_cb(n_delivered, seq_cmd, list(records))

            if run_cfg.inter_command_delay_ms > 0:
                time.sleep(run_cfg.inter_command_delay_ms / 1000.0)

    finally:
        client.disconnect()

    return records, n_delivered
